on:
  discord:
jobs:
  tweet:
    name: Send a tweet
    runs-on: ubuntu-latest
    steps:
      - name: Send a tweet
        uses: ethomson/send-tweet-action@v1
        with:
          status: ${{ on.discord.outputs.message }}
          consumer-key: ${{ secrets.TWITTER_CONSUMER_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
